Oyun-Teknolojileri/ToolKit

Editor/App.cpp
Editor/App.h
Editor/UI.cpp
Editor/UI.h
Editor/main.cpp

[TOOK-47](https://oyunteknolojileri.atlassian.net/browse/TOOK-47?atlOrigin=eyJpIjoiOWQyNzZjOTg5ZDI2NGEwZGEwNDNiOGM0NzQyN2M2YzQiLCJwIjoiaiJ9)

TOOK-47 Import Assets Directly

---

Editor/App.cpp
ToolKit/Renderer.cpp
ToolKit/ResourceComponent.cpp
ToolKit/ResourceComponent.h
ToolKit/Sky.cpp

[TOOK-449](https://oyunteknolojileri.atlassian.net/browse/TOOK-449?atlOrigin=eyJpIjoiMmUzY2MwMGZhMjM5NDQwM2FkMDNjODA1MmNhMmM0YmQiLCJwIjoiaiJ9)

TOOK-449 Environment Component AABB change

---

Editor/App.cpp
Editor/ConsoleWindow.cpp
Editor/FolderWindow.cpp
Editor/Global.h
Editor/UI.cpp
Editor/Workspace.cpp
Editor/main.cpp
ToolKit/Animation.cpp
ToolKit/Framebuffer.cpp
ToolKit/Material.cpp
ToolKit/ParameterBlock.cpp
ToolKit/ToolKit.cpp
ToolKit/Types.h

[TOOK-490](https://oyunteknolojileri.atlassian.net/browse/TOOK-490?atlOrigin=eyJpIjoiOWE0OWZlMzdiZDkwNDQ5OWFlNjViZTc1YTg1MmQ2YjIiLCJwIjoiaiJ9)

TOOK-490 AppData Folder fixes

---

Import/import.cpp

[TOOK-527](https://oyunteknolojileri.atlassian.net/browse/TOOK-527?atlOrigin=eyJpIjoiM2RmYjE4MWMxOWIzNDMwZWE4NjEwODUyYWMzNmMxNTgiLCJwIjoiaiJ9)

T-Pose bug fix

---

Editor/App.cpp
Editor/Editor.vcxproj
Editor/Editor.vcxproj.filters
Editor/FolderWindow.cpp
Editor/MaterialView.cpp
Editor/MaterialView.h
Editor/MeshView.cpp
Editor/MeshView.h
Editor/PropInspector.cpp
Editor/PropInspector.h
Editor/UI.h

[TOOK-534](https://oyunteknolojileri.atlassian.net/browse/TOOK-534?atlOrigin=eyJpIjoiNTM5M2RmMjE3Zjc3NDYyMWFmNDRlZmE1ZmY0YmJjMTIiLCJwIjoiaiJ9)

TOOK-534 Mesh View

---

Editor/MaterialView.cpp
Resources/Engine/Shaders/defaultFragment.shader
Resources/Engine/Shaders/solidColorFrag.shader
Resources/Engine/Shaders/unlitColorFrag.shader
Resources/Engine/Shaders/unlitFrag.shader
ToolKit/Pass.cpp
ToolKit/RenderState.cpp
ToolKit/RenderState.h
ToolKit/Renderer.cpp
ToolKit/Shader.cpp
ToolKit/Shader.h

TODO: change name in shader "alphaMask" to "alphaMaskTreshold"

Alpha Mask Blend Mode

---

Editor/App.cpp
Import/import.cpp

[TOOK-552](https://oyunteknolojileri.atlassian.net/browse/TOOK-552?atlOrigin=eyJpIjoiZjQyOTRhNjIxMDUyNDA3ZDlhNDhjODIxODBjYmFjNWQiLCJwIjoiaiJ9)

TOOK-552 Import improvements

---

Editor/EditorPass.cpp
Editor/EditorPass.h
ToolKit/Renderer.cpp
ToolKit/Renderer.h

[TOOK-521](https://oyunteknolojileri.atlassian.net/browse/TOOK-521?atlOrigin=eyJpIjoiZThkODc4MmFiMDJmNDgyNzgyYjdiNTZkZDVhMmZjMDEiLCJwIjoiaiJ9)

TOOK-521 Lighting Fix

---

Editor/MaterialView.cpp
Resources/Engine/Shaders/emissiveFrag.shader
ToolKit/BinPack2D.h
ToolKit/Material.cpp
ToolKit/Material.h
ToolKit/Mesh.cpp
ToolKit/Pass.h
ToolKit/RenderState.cpp
ToolKit/RenderState.h
ToolKit/Renderer.cpp
ToolKit/Shader.cpp
ToolKit/Shader.h
ToolKit/Types.h

[TOOK-473](https://oyunteknolojileri.atlassian.net/browse/TOOK-473?atlOrigin=eyJpIjoiZWViZWIxMzRmMDVhNGNlNDlkNmNjZTcwNzZjYTAyMzgiLCJwIjoiaiJ9)

TOOK-473 Emissive Material

---

Editor/App.cpp
Editor/App.h
Editor/Editor.vcxproj
Editor/Editor.vcxproj.filters
Editor/EditorPass.cpp
Editor/EditorPass.h
Editor/PropInspector.cpp
Editor/PropInspector.h
Editor/RenderSettingsView.cpp
Editor/RenderSettingsView.h
Resources/Engine/Shaders/tonemapFrag.shader
ToolKit/Pass.cpp
ToolKit/Pass.h
ToolKit/Renderer.cpp
ToolKit/ToolKit.cpp
ToolKit/ToolKit.h

[TOOK-475](https://oyunteknolojileri.atlassian.net/browse/TOOK-475?atlOrigin=eyJpIjoiMDIxYTQ0ZGNkZGZlNGU5OGJjZTYxMzI4YjVlNmQzYzAiLCJwIjoiaiJ9)

Took 475 ton mapping reinhard aces

---

Editor/EditorPass.cpp
Editor/EditorPass.h
Editor/FolderWindow.cpp
Editor/PopupWindows.cpp
Editor/PopupWindows.h
Editor/PropInspector.cpp
Editor/RenderSettingsView.cpp
Resources/Engine/Shaders/bloomDownsample.shader
Resources/Engine/Shaders/bloomUpsample.shader
ToolKit/Material.cpp
ToolKit/Pass.cpp
ToolKit/Pass.h
ToolKit/RenderState.h
ToolKit/Renderer.cpp
ToolKit/ToolKit.h

[TOOK-474](https://oyunteknolojileri.atlassian.net/browse/TOOK-474?atlOrigin=eyJpIjoiZTkyYzQyMGU1YjdhNGUxOWE0YTE1ZjVlYmUzODY2YmMiLCJwIjoiaiJ9)

Took 474 bloom

---

Editor/MaterialView.cpp
Editor/PropInspector.cpp
Resources/Engine/Shaders/deferredRenderFrag.shader
Resources/Engine/Shaders/gBufferFrag.shader
Resources/Engine/Shaders/lighting.shader
ToolKit/Material.cpp
ToolKit/Pass.cpp
ToolKit/Pass.h
ToolKit/Renderer.cpp

[TOOK-587](https://oyunteknolojileri.atlassian.net/browse/TOOK-587?atlOrigin=eyJpIjoiYTkzMjkxMjA5MjE3NDU3YTgyM2MyMDQwMmQyMzMwMDMiLCJwIjoiaiJ9)

Took 587 textured emissive for deferred rendering

---

Editor/PropInspector.cpp
ToolKit/Scene.cpp

[TOOK-543](https://oyunteknolojileri.atlassian.net/browse/TOOK-543?atlOrigin=eyJpIjoiNTI4MDViMWU3NTkwNGNiMWIyM2MxNWUzZDA2ZmVkMTEiLCJwIjoiaiJ9)

TOOK-543 Fix Memory Leak

---

Editor/EditorPass.cpp
Editor/EditorPass.h
Resources/Engine/Shaders/defaultFragment.shader
ToolKit/Renderer.cpp
ToolKit/Shader.cpp
ToolKit/Shader.h

[TOOK-520](https://oyunteknolojileri.atlassian.net/browse/TOOK-520?atlOrigin=eyJpIjoiZGVlOGJhZGMwNjlhNDUzYmI0NDYyODI3MzA4NTBmYzUiLCJwIjoiaiJ9)

Took 520 lighting only mode uses editor lights

---

Editor/PropInspector.cpp
ToolKit/UIManager.cpp

[TOOK-620](https://oyunteknolojileri.atlassian.net/browse/TOOK-620?atlOrigin=eyJpIjoiYWRkOTY5NDY2NDExNGVkYTk1Nzc0NzY4ZTRiZWQ2N2YiLCJwIjoiaiJ9)

TOOK-620 Fix Scroll Problem

---

ToolKit/Mesh.h
ToolKit/Renderer.cpp

[TOOK-621](https://oyunteknolojileri.atlassian.net/browse/TOOK-621?atlOrigin=eyJpIjoiNjk1N2RiZWY5ZDZkNGM4NTgyOTI1OTRkOWQ0Y2YzNDMiLCJwIjoiaiJ9)

TOOK-621 SkinMesh Rendering Fix

---

Editor/EditorPass.cpp
Editor/EditorPass.h
Resources/Engine/Shaders/fxaaFilterFrag.shader
ToolKit/PostProcessPass.cpp
ToolKit/PostProcessPass.h

- FXAA implemenation based on ShaderToy sample at https://www.shadertoy.com/view/4tf3D8

TOOK-634 fxaa implementation

---

Resources/Engine/Shaders/defaultVertex.shader
Resources/Engine/Shaders/skinning.shader

[TOOK-647](https://oyunteknolojileri.atlassian.net/browse/TOOK-647?atlOrigin=eyJpIjoiYzI5MzRkMmYwYzM1NDkzYzhjZjI0NTA1YjhlNGFiZmYiLCJwIjoiaiJ9)

TOOK-647 SkinMesh Lighting Fix

---

Editor/ComponentView.cpp
Editor/PropInspector.cpp
Editor/RenderSettingsView.cpp
Resources/Engine/Shaders/depthOfFieldFrag.shader
ToolKit/FileManager.cpp
ToolKit/Framebuffer.h
ToolKit/Material.cpp
ToolKit/PostProcessPass.cpp
ToolKit/PostProcessPass.h
ToolKit/SceneRenderer.cpp
ToolKit/SceneRenderer.h
ToolKit/Sky.cpp
ToolKit/Texture.h
ToolKit/ToolKit.h

[TOOK-272](https://oyunteknolojileri.atlassian.net/browse/TOOK-272?atlOrigin=eyJpIjoiYmQ3ZTdjMWRiMGYyNDZmN2E0NDcxNGM3YWU4MzU4NzIiLCJwIjoiaiJ9)

Took 272 implement bokeh do f

---

Editor/ComponentView.cpp
Editor/EditorViewport.cpp
Editor/MaterialView.cpp
Import/import.cpp
ToolKit/MathUtil.cpp
ToolKit/MathUtil.h
ToolKit/ResourceComponent.cpp
ToolKit/Scene.cpp

[TOOK-649](https://oyunteknolojileri.atlassian.net/browse/TOOK-649?atlOrigin=eyJpIjoiOGMyNzJmMzlkNjk1NDg5NzhlNGQ1OTdjMGQ4MDcyZmUiLCJwIjoiaiJ9)

TOOK-649 Drag&Drop Material Fix

---

Editor/EditorCamera.cpp

[TOOK-661](https://oyunteknolojileri.atlassian.net/browse/TOOK-661?atlOrigin=eyJpIjoiNWY3NTFjZDVlYjU4NDFiN2IxNjFhOGYzODYwMjYyNjAiLCJwIjoiaiJ9)

TOOK-661 Camera Bugs Fix

---

Editor/EditorPass.cpp
Editor/RenderSettingsView.cpp
Editor/Workspace.cpp
Editor/Workspace.h
ToolKit/Scene.cpp
ToolKit/Scene.h
ToolKit/SceneRenderer.h
ToolKit/ToolKit.cpp
ToolKit/ToolKit.h

Graphic and Window settings are  located in Engine.settings and post processing settings are located in SceneX.scene

Unique Post processing for each scene

---

ToolKit/Renderer.cpp

I think this is more clean and understandable.

implementation.

---

Editor/ConsoleWindow.cpp
ToolKit/Entity.cpp
ToolKit/Entity.h
ToolKit/MathUtil.cpp
ToolKit/Pass.cpp
ToolKit/Prefab.cpp
ToolKit/Prefab.h
ToolKit/Scene.cpp
ToolKit/ShadowPass.cpp
ToolKit/Util.h

when prefab saved as invisible but child's are visible in that case child's shouldn't show up but they are showing up. 
I fix this issue by deep set visible.

problem fixed, idk is there any better way of doing this,

---

Editor/FolderWindow.cpp
Editor/FolderWindow.h
Import/import.cpp
ToolKit/Node.cpp
ToolKit/Scene.cpp

this was causing bugs when we import skeletal meshes and want to delete empty nodes.

Another import fix

---

Editor/main.cpp
ToolKit.sln
ToolKit/Renderer.cpp
ToolKit/Shader.cpp
ToolKit/Shader.h
ToolKit/ToolKit.cpp
ToolKit/ToolKit.h

added Time variable to feed uniforms.

---

Editor/App.cpp
Editor/PluginWindow.cpp
Editor/PluginWindow.h
Editor/Workspace.cpp
Editor/Workspace.h
ToolKit/ToolKit.cpp

implemented saving and loading simulation resolution settings.
I've solved the warnings but we still have some warnings but that warnings will be gone when we merge asset browser pr.

Run in window save last res took 805

---

Editor/App.cpp
Resources/Engine/Shaders/fxaaFilterFrag.shader
ToolKit/Logger.cpp
ToolKit/Logger.h
ToolKit/Shader.cpp

basicly same shader but more convinient and has comments. +added output console log for shader errors.
// https://mini.gmshaders.com/p/gm-shaders-mini-fxaa

Fxaa improvements

---

Editor/App.cpp
ToolKit/Logger.cpp
ToolKit/Logger.h

we write to console but we don't have a way to clear to console so I added a function to logger
GetLogger()->ClearConsole();

clear console abstraction

---

Editor/OutlinerWindow.cpp
Editor/OutlinerWindow.h
Editor/UI.cpp

I've also added right click and delete the selected item. right click to selected node actions was only SaveAsPrefab but now we can right click and chose delete to delete selected entities.
also we can now click empty space in outliner window to deselect all selected nodes

adding removing child works fine.

---

Editor/FolderView.cpp
Editor/Gizmo.cpp
Editor/Mod.cpp
Editor/OutlinerWindow.cpp
Editor/OutlinerWindow.h
Editor/PopupWindows.cpp
Editor/TopBar.cpp
Editor/TopBar.h
Editor/UI.cpp
ToolKit/Entity.cpp
ToolKit/Entity.h
ToolKit/Node.cpp
ToolKit/Node.h
ToolKit/Primative.cpp
ToolKit/Scene.cpp
ToolKit/Scene.h
ToolKit/Util.cpp
ToolKit/Util.h

Reordering is done!
also I've added right click to create entities in outliner window ( same as top bar add)
created entity will placed to where you right clicked. (uses same algorithm with reordering.)
and naming is better now. (for example SpotLight_0 instead of Entity_1453)

algorithm implemented.

---

Editor/ComponentView.cpp

showCompFunc was drawing the multimaterial and we were also drawing it with  ShowMultiMaterialComponent function 
so I solved with one if block, other changes that you see are indentations.

Fix duplicate material view problem.

---

Editor/EditorLight.cpp
Editor/LightMeshGenerator.cpp
Resources/Engine/Shaders/additiveLighting.shader
Resources/Engine/Shaders/additivePBRLighting.shader
Resources/Engine/Shaders/additiveVertex.shader
Resources/Engine/Shaders/deferredRenderFrag.shader
ToolKit/AdditiveLightingPass.cpp
ToolKit/AdditiveLightingPass.h
ToolKit/DeferredPass.cpp
ToolKit/GeometryTypes.h
ToolKit/Light.cpp
ToolKit/Light.h
ToolKit/MathUtil.cpp
ToolKit/MathUtil.h
ToolKit/Primative.cpp
ToolKit/Primative.h
ToolKit/RenderState.h
ToolKit/SceneRenderer.cpp
ToolKit/ToolKit.h
ToolKit/Types.h

we discard, spot and point lights with frustum culling and depth test now

Light culling, Pixel culling

---

Editor/AnchorMod.cpp
Editor/EditorViewport.cpp
Editor/EditorViewport2d.cpp
Editor/EditorViewport2d.h

editor viewport init was not getting called during derserialization, because of that snap values were arriving 0

TOOK-902-SnapFix

---

ToolKit/Logger.cpp
ToolKit/Resource.cpp

use get file while deserialize.
Log all available consoles.

TOOK-904-Crash-non-existing-assets.

---

Editor/App.cpp
Editor/App.h
Editor/DynamicMenu.cpp
Editor/DynamicMenu.h
Editor/Editor.vcxproj
Editor/Editor.vcxproj.filters
Editor/TopBar.cpp
Editor/main.cpp
Template/CMakeLists.txt
ToolKit/Class.h
ToolKit/Component.cpp
ToolKit/Component.h
ToolKit/Meta.h
ToolKit/ObjectFactory.cpp
ToolKit/ObjectFactory.h
ToolKit/Primative.cpp
ToolKit/Primative.h
ToolKit/TKOpenGL.cpp
ToolKit/TKOpenGL.h
ToolKit/ToolKit.cpp
ToolKit/ToolKit.vcxproj
ToolKit/ToolKit.vcxproj.filters

With this PR Entity types created in the game plugins can be dynamically registered to the engine and can be created from Add menu.
Dynamic Menu in Editor
How to register new types ( This is just an example, we can register the custom types from game plugins )
Real example
```
class MyCustomClass : public Entity
{
TKDeclareClass(MyCustomClass, Entity)
}
TKDefineClass(MyCustomClass, Entity)
MyCustomClass::StaticClass()->MetaKeys[MenuMetaKey] = "MyCustomGameObjects/MyCustomClass:Enemy1";
GetObjectFactory()->Register<MyCustomClass>();
```

TOOK-911-Dynamic Object Menu

---

BuildScripts/WebBuildDebug.bat
BuildScripts/WebBuildRelease.bat
BuildScripts/WebBuildReleaseWithDeb.bat
Editor/App.cpp
Editor/EditorScene.cpp
Editor/OutlinerWindow.cpp
Editor/OutlinerWindow.h
Editor/PublishManager.cpp
Editor/UI.h
Editor/main.cpp
Template/Codes/.vscode/c_cpp_properties.json
Template/Codes/.vscode/launch.json
Template/Codes/CMakeLists.txt
Template/Codes/Game.cpp
Template/Codes/Game.h
ToolKit/CMakeLists.txt
ToolKit/DebugNew.h
ToolKit/Mesh.cpp
ToolKit/Object.h

When creating new project, 
we add c++ configurations automatically
update cmake versions
fix for numerical local

New Project fixes

---

Editor/Editor.vcxproj.user
Editor/PublishManager.cpp

fix current path, remove redundant packing.

Fix packing

---

BuildScripts/WebBuildDebug.bat
BuildScripts/WebBuildRelease.bat
BuildScripts/WebBuildReleaseWithDeb.bat
Editor/Editor.vcxproj
Editor/Editor.vcxproj.user
Import/Import.vcxproj
Packer/Packer.vcxproj
Template/Android/app/jni/src/android_main.cpp
Template/Template.vcxproj
Template/Template.vcxproj.user
Template/Web/WebBuildDebug.bat
Template/Web/WebBuildRelease.bat
Template/Web/web_main.cpp
Template/Windows/win_main.cpp
ToolKit.sln
ToolKit/MathUtil.cpp
ToolKit/MathUtil.h
ToolKit/Mesh.cpp
ToolKit/ToolKit.vcxproj

Add profile configuration to visual studio.
Fix crash in cpu skinning ( broken asset send wrong skeleton for the mesh )
Add parallel execution to emscripten
SetViewport runs once after the toolkit initialized in templates ( android, web, pc )

Profile configuration

---

Resources/Engine/Shaders/lighting.shader
Resources/Engine/Shaders/shadow.shader
ToolKit/LightDataBuffer.cpp
ToolKit/LightDataBuffer.h
ToolKit/ShadowPass.cpp

For a given texture which consist of N sub textures, when the start position of the texture provided, exact layer and coordinates calculated programatically in the shader.

Atlas LookUp Function is added in to shader

---

Editor/RenderSettingsWindow.cpp
Resources/Engine/Shaders/orthogonalDepthFrag.shader
Resources/Engine/Shaders/perspectiveDepthFrag.shader
Resources/Engine/Shaders/shadow.shader
ToolKit/EngineSettings.h
ToolKit/ForwardPass.cpp
ToolKit/Light.cpp
ToolKit/Light.h
ToolKit/Shader.cpp
ToolKit/ShadowPass.cpp
ToolKit/ShadowPass.h

EVSM 2 component does not produce good results with filtering under certain conditions. 4 Components yields perfect results under all conditions.

EVSM4 Component Shadow Map

---

BuildScripts/Build.bat
BuildScripts/WinBuildDebug.bat
BuildScripts/WinBuildRelWithDebugInfo.bat
BuildScripts/WinBuildRelease.bat
Import/Import.vcxproj
Packer/Packer.cpp
Packer/Packer.vcxproj
Templates/Game/Codes/Main.cpp
Templates/Game/Windows/Build.bat
Templates/Game/Windows/WinBuildDebug.bat
Templates/Game/Windows/WinBuildRelWithDebugInfo.bat
Templates/Game/Windows/WinBuildRelease.bat
ToolKit/GameRenderer.h
ToolKit/Renderer.cpp
ToolKit/Renderer.h
ToolKit/Shader.cpp
ToolKit/Shader.h

Editor build of games fixed for windows,
Publishing for windows fixed.
Multiple build scripts accumulated to a single one with arguments

Windows publishing fixes

---

Editor/App.cpp
Editor/FolderView.cpp
Editor/FolderWindow.cpp
Editor/FolderWindow.h
Editor/OutlinerWindow.cpp
Import/import.cpp
ToolKit/Prefab.h
ToolKit/RenderSystem.cpp
ToolKit/Scene.cpp
ToolKit/Scene.h
ToolKit/Util.cpp

Asset browser only shows the tabs up to current folder.
Copy / Delete / Rename crash fixes.

Asset Browser fixes

---

Editor/EditorScene.cpp
Editor/EditorScene.h
ToolKit/AABBTree.cpp
ToolKit/AABBTree.h
ToolKit/ForwardPreProcessPass.cpp
ToolKit/ForwardPreProcessPass.h
ToolKit/Framebuffer.cpp
ToolKit/Renderer.cpp
ToolKit/Scene.cpp
ToolKit/Scene.h
ToolKit/StencilPass.cpp
ToolKit/TKStats.cpp
ToolKit/Texture.cpp

fixes sticky ao ( render target was not getting set properly so ao texture was not receiving update )

Forward Pre Pass Render Target Setting Fix

---

Editor/TransformMod.cpp
ToolKit/Node.cpp

Rotate / Translate fixes for corresponding spaces

Transform Node Fixes

---

Editor/App.cpp
Editor/App.h
Editor/EditorCamera.cpp
Editor/EditorTypes.h
Editor/EditorViewport.cpp
Editor/EditorViewport2d.cpp
Editor/PublishManager.cpp
Editor/StatusBar.cpp
Editor/Thumbnail.cpp
Editor/Thumbnail.h
Editor/UI.cpp
Editor/UI.h
ToolKit/EngineSettings.cpp
ToolKit/Prefab.cpp
ToolKit/Prefab.h
ToolKit/Scene.cpp
ToolKit/Skeleton.cpp
ToolKit/Threads.cpp
ToolKit/Threads.h
ToolKit/Types.h
ToolKit/stdafx.h

A thread pool is created for background loading operations.
Scene loading and thumbnail creating is performed in the background.

Async asset loading
